#!/usr/bin/env python3
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    the_workshop_team
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Mon Sep  6 11:40:44 2021
#
##############################################################################

# %module
# % description: Script generated by wxGUI Graphical Modeler.
# %end
# %option
# % key: elevation
# % description: Name of input elevation
# % type: string
# % key_desc: name
# % answer: dtm_5606
# %end
# %option
# % key: height
# % description: Elevation threshold
# % type: integer
# % answer: 500
# %end
# %option
# % key: slope
# % description: Slope threshold
# % type: integer
# % answer: 10
# %end

import sys
import os
import atexit

from grass.script import parser
from grass.pygrass.modules import Module

def cleanup():
    pass

def main(options, flags):
    Module("g.region",
           raster=options["elevation"])

    Module("r.slope.aspect",
           elevation=options["elevation"],
           slope="slope_aoi",
           format="degrees",
           precision="FCELL",
           zscale=1.0,
           min_slope=0.0)

    Module("r.mapcalc",
           expression=f"dtm_slope = if({options['elevation']} > {options['height']} && slope_aoi > {options['slope']}, {options['elevation']}, null())",
           region="current")

    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    os.environ["GRASS_OVERWRITE"] = "1"
    sys.exit(main(options, flags))
