#!/usr/bin/env python3
#
##############################################################################
#
# MODULE:       model
#
# AUTHOR(S):    the_workshop_team
#
# PURPOSE:      Script generated by wxGUI Graphical Modeler.
#
# DATE:         Mon Sep  6 11:40:44 2021
#
##############################################################################

# %module
# % description: Script generated by wxGUI Graphical Modeler.
# %end
# %option
# % key: gregion1_raster
# % description: Set region to match raster map(s)
# % required: yes
# % type: string
# % key_desc: name
# % answer: dtm_5606
# %end
# %option
# % key: rslopeaspect2_elevation
# % description: Name of input elevation raster map
# % required: yes
# % type: string
# % key_desc: name
# % answer: dtm_5606
# %end
# %option
# % key: rmapcalc3_expression
# % description: Expression to evaluate
# % required: yes
# % type: string
# % answer: dtm_slope = if(dtm_5606 > 500 && slope_aoi > 10, dtm_5606)
# %end

import sys
import os
import atexit

from grass.script import parser
from grass.pygrass.modules import Module

def cleanup():
    pass

def main(options, flags):
    Module("g.region",
           raster=options["gregion1_raster"])

    Module("r.slope.aspect",
           elevation=options["rslopeaspect2_elevation"],
           slope="slope_aoi",
           aspect="aspect_aoi",
           format="degrees",
           precision="FCELL",
           zscale=1.0,
           min_slope=0.0)

    Module("r.mapcalc",
           expression=options["rmapcalc3_expression"],
           region="current")

    return 0

if __name__ == "__main__":
    options, flags = parser()
    atexit.register(cleanup)
    os.environ["GRASS_OVERWRITE"] = "1"
    sys.exit(main(options, flags))
